CONTAINER squaretube
{
  NAME squaretube;
  INCLUDE Obase;

  GROUP ID_OBJECTPROPERTIES
  {
    REAL PY_SQUARETUBE_LENGTH       { UNIT METER; MIN 0.0; }
    REAL PY_SQUARETUBE_WIDTH        { UNIT METER; MIN 0.0; }
    REAL PY_SQUARETUBE_DEPTH        { UNIT METER; MIN 0.0; }
    REAL PY_SQUARETUBE_THICKNESS    { UNIT METER; MIN 0.0; STEP 0.05; }
    REAL PY_SQUARETUBE_TOP_ANGLE    { UNIT DEGREE; MIN 0.0; MAX 89.9; }
    REAL PY_SQUARETUBE_BOTTOM_ANGLE { UNIT DEGREE; MIN 0.0; MAX 89.9; }
  }

  INCLUDE Oprimitiveaxis;
}
